In [ ]:
                                                 # Exploratory Data Analysis (EDA Basics)

In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
df=pd.read_csv('House Price India.csv')
df.head()

,id,Date,number of bedrooms,number of bathrooms,living area,lot area,number of floors,waterfront present,number of views,condition of the house,...,Built Year,Renovation Year,Postal Code,Lattitude,Longitude,living_area_renov,lot_area_renov,Number of schools nearby,Distance from the airport,Price
0,6762810145,42491,5,2.50,3650,9050,2.0,0,4,5,...,1921,0,122003,52.8645,-114.557,2880,5400,2,58,2380000
1,6762810635,42491,4,2.50,2920,4000,1.5,0,0,5,...,1909,0,122004,52.8878,-114.470,2470,4000,2,51,1400000
2,6762810998,42491,5,2.75,2910,9480,1.5,0,0,3,...,1939,0,122004,52.8852,-114.468,2940,6600,1,53,1200000
3,6762812605,42491,4,2.50,3310,42998,2.0,0,0,3,...,2001,0,122005,52.9532,-114.321,3350,42847,3,76,838000
4,6762812919,42491,3,2.00,2710,4500,1.5,0,0,4,...,1929,0,122006,52.9047,-114.485,2060,4500,1,51,805000

In [ ]:
# Problem Satatement - House Price Analysis
# You are a data analysis working with real estate data. Your task is to analyze the dataset to understand:
# Individual variable behaviour (Univariate Analysis)
# Business insights from relationship (interpersonal)

In [ ]:
Assignment Tasks
Instructions
# 1 Load the dataset
# 2 Perform basic checks using:
df.info()
df.describe()
# 3 Handel missing values(if any)
# 4 Solve the questions using Pandas operations
# 5 Provide interpretation for each answer

In [6]:
# 2-

df.shape

(14620, 23)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14620 entries, 0 to 14619
Data columns (total 23 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   id                                     14620 non-null  int64
 1   Date                                   14620 non-null  int64
 2   number of bedrooms                     14620 non-null  int64
 3   number of bathrooms                    14620 non-null  float64
 4   living area                            14620 non-null  int64
 5   lot area                               14620 non-null  int64
 6   number of floors                       14620 non-null  float64
 7   waterfront present                     14620 non-null  int64
 8   number of views                        14620 non-null  int64
 9   condition of the house                 14620 non-null  int64
 10  grade of the house                     14620 non-null  int64
 11  Area of the house(excluding basement)  14620 non-null  int64
 12  Area of the basement                   14620 non-null  int64
 13  Built Year                             14620 non-null  int64
 14  Renovation Year                        14620 non-null  int64
 15  Postal Code                            14620 non-null  int64
 16  Lattitude                              14620 non-null  float64
 17  Longitude                              14620 non-null  float64
 18  living_area_renov                      14620 non-null  int64
 19  lot_area_renov                         14620 non-null  int64
 20  Number of schools nearby               14620 non-null  int64
 21  Distance from the airport              14620 non-null  int64
 22  Price                                  14620 non-null  int64
dtypes: float64(4), int64(19)
memory usage: 2.6 MB

In [7]:
df.describe()

,id,Date,number of bedrooms,number of bathrooms,living area,lot area,number of floors,waterfront present,number of views,condition of the house,...,Built Year,Renovation Year,Postal Code,Lattitude,Longitude,living_area_renov,lot_area_renov,Number of schools nearby,Distance from the airport,Price
count,1.462000e+04,14620.000000,14620.000000,14620.000000,14620.000000,1.462000e+04,14620.000000,14620.000000,14620.000000,14620.000000,...,14620.000000,14620.000000,14620.000000,14620.000000,14620.000000,14620.000000,14620.000000,14620.000000,14620.000000,1.462000e+04
mean,6.762821e+09,42604.538646,3.379343,2.129583,2098.262996,1.509328e+04,1.502360,0.007661,0.233105,3.430506,...,1970.926402,90.924008,122033.062244,52.792848,-114.404007,1996.702257,12753.500068,2.012244,64.950958,5.389322e+05
std,6.237575e+03,67.347991,0.938719,0.769934,928.275721,3.791962e+04,0.540239,0.087193,0.766259,0.664151,...,29.493625,416.216661,19.082418,0.137522,0.141326,691.093366,26058.414467,0.817284,8.936008,3.675324e+05
min,6.762810e+09,42491.000000,1.000000,0.500000,370.000000,5.200000e+02,1.000000,0.000000,0.000000,1.000000,...,1900.000000,0.000000,122003.000000,52.385900,-114.709000,460.000000,651.000000,1.000000,50.000000,7.800000e+04
25%,6.762815e+09,42546.000000,3.000000,1.750000,1440.000000,5.010750e+03,1.000000,0.000000,0.000000,3.000000,...,1951.000000,0.000000,122017.000000,52.707600,-114.519000,1490.000000,5097.750000,1.000000,57.000000,3.200000e+05
50%,6.762821e+09,42600.000000,3.000000,2.250000,1930.000000,7.620000e+03,1.500000,0.000000,0.000000,3.000000,...,1975.000000,0.000000,122032.000000,52.806400,-114.421000,1850.000000,7620.000000,2.000000,65.000000,4.500000e+05
75%,6.762826e+09,42662.000000,4.000000,2.500000,2570.000000,1.080000e+04,2.000000,0.000000,0.000000,4.000000,...,1997.000000,0.000000,122048.000000,52.908900,-114.315000,2380.000000,10125.000000,3.000000,73.000000,6.450000e+05
max,6.762832e+09,42734.000000,33.000000,8.000000,13540.000000,1.074218e+06,3.500000,1.000000,4.000000,5.000000,...,2015.000000,2015.000000,122072.000000,53.007600,-113.505000,6110.000000,560617.000000,3.000000,80.000000,7.700000e+06

In [8]:
df.isnull().sum()

id                                       0
Date                                     0
number of bedrooms                       0
number of bathrooms                      0
living area                              0
lot area                                 0
number of floors                         0
waterfront present                       0
number of views                          0
condition of the house                   0
grade of the house                       0
Area of the house(excluding basement)    0
Area of the basement                     0
Built Year                               0
Renovation Year                          0
Postal Code                              0
Lattitude                                0
Longitude                                0
living_area_renov                        0
lot_area_renov                           0
Number of schools nearby                 0
Distance from the airport                0
Price                                    0
dtype: int64

In [ ]:
# 3
Handel missing values if found any
# Answer - There is no null values in the dataset.

In [ ]:
Assignment Questions

Q1- What is the average,median,and standard deviation of house prices?

Q2- Which number of bedrooms is most common?

Q3- Check if the price data is skewed.
    
Q4- What is the average price for each number of bedrooms?

Q5- What is the relationship between living area and price?( Use: Area without Basement).
    
Q6- Identify anomalies where houses have high prices but low areas.
    
Q7- Compare average price based on number of floors and houses with or without waterfront.
    
Q8- Identify the minimum and maximum house price.What does this indicate?
    
Q9- Which location (zipcode/area) has the highest average price?
    
Q10- Write at least 5 insights from your analysis.

In [14]:
# Q1- 
df['Price'].mean()

np.float64(538932.2183310534)

In [15]:
df['Price'].median()

450000.0

In [18]:
df['Price'].std()

367532.3808039669

In [ ]:
Q2- Which number of bedrooms is most common?

In [ ]:
most_common_bhk=df['number of bedrooms'].mode()

In [22]:
df['number of bedrooms'].mode()

0    3
Name: number of bedrooms, dtype: int64

In [ ]:
Q3- Check if the price data is skewed.

In [23]:
skewness =df['Price'].skew()

In [24]:
print(skewness)

4.269297720707117

In [ ]:
Q4- What is the average price for each number of bedrooms?

In [28]:
df.groupby('number of bedrooms')['Price'].mean().sort_index()

number of bedrooms
1     3.089638e+05
2     3.985476e+05
3     4.632776e+05
4     6.361988e+05
5     7.752550e+05
6     8.375815e+05
7     1.016544e+06
8     1.208455e+06
9     7.766663e+05
10    8.200000e+05
11    5.200000e+05
33    6.400000e+05
Name: Price, dtype: float64

In [ ]:
Q5- What is the relationship between living area and price?( Use: Area without Basement).

In [30]:
correlation=df['living area'].corr(df['Price'])

In [31]:
print(correlation)

0.7121694766782516

In [ ]:
Q6- Identify anomalies where houses have high prices but low areas.

In [ ]:
# Anamalies - High price but Low area

In [12]:
Q1_area=df['living area'].quantile(0.25)
Q3_area=df['living area'].quantile(0.75)
IQR_area=Q3_area - Q1_area
low_area_cutoff=Q1_area-1.5* IQR_area

Q3_price=df['Price'].quantile(0.75)
high_price_cutoff=Q3_price  # top 25% percent prices

anomolies=df[(df['living area']<low_area_cutoff)&(df['Price']>high_price_cutoff)]
print(anomolies[['Price','living area']])

Empty DataFrame
Columns: [Price, living area]
Index: []

In [10]:
#Q7- Compare average price based on number of floors and houses with or without waterfront.

In [32]:
df.groupby(['number of floors','waterfront present'])['Price'].mean()

number of floors  waterfront present
1.0               0                     4.323724e+05
                  1                     1.211081e+06
1.5               0                     5.476162e+05
                  1                     1.232507e+06
2.0               0                     6.357742e+05
                  1                     2.075931e+06
2.5               0                     1.087654e+06
                  1                     3.280000e+06
3.0               0                     5.558095e+05
                  1                     1.655000e+06
3.5               0                     1.205875e+06
Name: Price, dtype: float64

In [ ]:
Q8- Identify the minimum and maximum house price.What does this indicate?

In [34]:
min_price=df['Price'].min()
max_price=df['Price'].max()

In [35]:
print(min_price,max_price)

78000 7700000

In [ ]:
Q9- Which location (zipcode/area) has the highest average price?

In [39]:
df.groupby(['Postal Code'])['Price'].mean().sort_values(ascending=False)

Postal Code
122071    2.348311e+06
122048    1.296414e+06
122057    1.188517e+06
122047    1.069295e+06
122061    8.895896e+05
              ...
122070    2.799618e+05
122039    2.752509e+05
122066    2.487003e+05
122072    2.342158e+05
122056    2.335950e+05
Name: Price, Length: 70, dtype: float64

In [ ]:
Q10- Write at least 5 insights from your analysis.

In [ ]:
1- Price is positively skewed 
2-3 bhk is most common,but 4+ bhk has highest price jump per room.
3- Living area has 0.7+ correlation with price - size matters most
4- Waterfall properties have 2x average price vs non-waterfront
5- Anomalies exist: 10% of houses are small but priced in top 25% due to location.