In [4]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\programdata\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [1]:
import pandas as pd

In [2]:
pd.__version__

'2.3.3'

In [3]:
df=pd.read_csv("retail_datasett_.csv")

In [ ]:
# Question 1:- Load the given retail sales dataset into a pandas Dataframe and display the first 5 rows 
               # along with the dataset information to understand its structure.

In [4]:
df

,Transaction ID,Customer ID,Product Category,Quantity,Price,Date,Region
0,T001,C015,Books,7.0,167.0,02-02-2023,North
1,T002,C004,Toys,4.0,374.0,17-02-2023,South
2,T003,C033,Furniture,8.0,1059.0,17-05-2024,South
3,T004,C047,Groceries,5.0,304.0,11-02-2024,South
4,T005,C022,Books,7.0,282.0,27-07-2024,West
...,...,...,...,...,...,...,...
95,T096,C036,Furniture,10.0,2901.0,08-08-2023,North
96,T097,C021,Clothing,9.0,1077.0,19-07-2024,North
97,T098,C015,Clothing,7.0,643.0,13-08-2023,North
98,T099,C005,Groceries,9.0,429.0,20-01-2024,South
99,T100,C010,Furniture,8.0,1183.0,07-02-2024,North

In [49]:
df.shape

(100, 7)

In [ ]:
# Question 2:- Inspect the dataset and identify missing values in each column. Display the total 
               # number of missing values present in the dataset.

In [8]:
df.isnull().sum()

Transaction ID      0
Customer ID         0
Product Category    3
Quantity            2
Price               5
Date                0
Region              2
dtype: int64

In [ ]:
# Question 3:- Replace missing values in the quantity and Price columns with their respective mean values using pandas.

In [17]:
# Filling Missing values in Quantity Column 
df['Quantity']=df['Quantity'].fillna(df['Quantity'].mean())

In [25]:
# removing missing values from price column 
df['Price']=df['Price'].fillna(df['Price'].mean())

In [46]:
df.isnull().sum()

Transaction ID      0
Customer ID         0
Product Category    3
Quantity            0
Price               0
Date                0
Region              2
dtype: int64

In [27]:
df.describe()

         Quantity        Price
count  100.000000   100.000000
mean     5.959184   820.526316
std      2.842386   595.536493
min      1.000000    92.000000
25%      3.750000   429.000000
50%      6.000000   722.500000
75%      8.000000   969.500000
max     10.000000  2901.000000

In [ ]:
# Question 5:- Create a new column called Revenue using Numpy,where:
# Revenue = Quantity*Price
# Display the updated dataset with the new column.

In [50]:
import numpy as np

In [52]:
df["Revenue"]=np.multiply(df["Quantity"],df["Price"])

In [53]:
df

,Transaction ID,Customer ID,Product Category,Quantity,Price,Date,Region,Revenue
0,T001,C015,Books,7.0,167.0,02-02-2023,North,1169.0
1,T002,C004,Toys,4.0,374.0,17-02-2023,South,1496.0
2,T003,C033,Furniture,8.0,1059.0,17-05-2024,South,8472.0
3,T004,C047,Groceries,5.0,304.0,11-02-2024,South,1520.0
4,T005,C022,Books,7.0,282.0,27-07-2024,West,1974.0
...,...,...,...,...,...,...,...,...
95,T096,C036,Furniture,10.0,2901.0,08-08-2023,North,29010.0
96,T097,C021,Clothing,9.0,1077.0,19-07-2024,North,9693.0
97,T098,C015,Clothing,7.0,643.0,13-08-2023,North,4501.0
98,T099,C005,Groceries,9.0,429.0,20-01-2024,South,3861.0
99,T100,C010,Furniture,8.0,1183.0,07-02-2024,North,9464.0

In [ ]:
# Question 6:- Using Numpy,calculate the total Revenue generated from all transections in the dataset.

In [61]:
total_revenue=np.sum(df["Revenue"])
print("Total Revenue from all the transections",total_revenue)

Total Revenue from all the transections 491834.8711063373

In [ ]:
# Question 7:-Group by Product Category-> Total Revenue per category

In [66]:
Category_revenue=df.groupby("Product Category")["Revenue"].sum()

In [67]:
print(Category_revenue)

Product Category
Beauty          28691.000000
Books           29597.938776
Clothing        85006.000000
Electronics     93204.315789
Furniture      129664.526316
Groceries       11978.000000
Sports          34484.000000
Toys            60512.090226
Name: Revenue, dtype: float64

In [ ]:
# Question 8:- Based on the revenue calculated for each product category,identify the top 3 categories with the highest
# revenue and the bottom 3 categories with the lowest revenue.

In [69]:
print(Category_revenue.nlargest(3))

Product Category
Furniture      129664.526316
Electronics     93204.315789
Clothing        85006.000000
Name: Revenue, dtype: float64

In [70]:
print(Category_revenue.nsmallest(3))

Product Category
Groceries    11978.000000
Beauty       28691.000000
Books        29597.938776
Name: Revenue, dtype: float64

In [ ]:
#Question 9:-Group the dataset by Region and Calculate the total revenue generated in each region. Identify the region 
# with the highest revenue and the region with the lowest revenue.

In [72]:
Region_revenue=df.groupby("Region")["Revenue"].sum()

In [73]:
print(Region_revenue)

Region
East     135184.044039
North    162989.353383
South    104855.736842
West      81197.526316
Name: Revenue, dtype: float64

In [77]:
print("Highest revenue region wise",df.Region,Region_revenue.max())

Highest revenue region wise 0     North
1     South
2     South
3     South
4      West
      ...
95    North
96    North
97    North
98    South
99    North
Name: Region, Length: 100, dtype: object 162989.35338345866

In [79]:
print("Lowest revenue region wise",df.Region,Region_revenue.min())

Lowest revenue region wise 0     North
1     South
2     South
3     South
4      West
      ...
95    North
96    North
97    North
98    South
99    North
Name: Region, Length: 100, dtype: object 81197.52631578947

In [ ]:
# Question 10:- Extract the month from the Data column using Pandas and group the dataset by month to calculate the 
# total monthly revenue. Also,calculate the mean,median,mode and standard deviation of the Revenue column using Numpy.

In [83]:
import pandas as pd

In [84]:
import numpy as np

In [89]:
df['Date']= pd.to_datetime(df['Date'],dayfirst=True,errors='coerce')

In [90]:
print(df['Date'].head(10))

0   2023-02-02
1          NaT
2          NaT
3   2024-11-02
4          NaT
5          NaT
6   2023-09-04
7          NaT
8          NaT
9          NaT
Name: Date, dtype: datetime64[ns]

In [92]:
print(df['Date'].isna().sum())

63

In [93]:
df['Month']=df['Date'].dt.month

In [94]:
Monthly_Revenue=df.groupby('Month')['Revenue'].sum()

In [95]:
print(Monthly_Revenue)

Month
1.0      2240.000000
2.0     18817.000000
3.0      3220.000000
4.0     13226.105263
5.0      5355.000000
6.0     17444.000000
7.0     24083.938776
8.0     34491.000000
9.0     26224.210526
10.0    39939.142857
11.0    11747.000000
12.0    13072.736842
Name: Revenue, dtype: float64

In [97]:
print("Mean",np.mean(df['Revenue']))

Mean 4918.348711063373

In [98]:
print("Median",np.median(df['Revenue']))

Median 3466.5

In [99]:
print("Standard Deviation",np.std(df['Revenue']))

Standard Deviation 4646.774020595719

In [101]:
df.describe()

,Quantity,Price,Date,Revenue,Month
count,100.000000,100.000000,37,100.000000,37.000000
mean,5.959184,820.526316,2024-03-11 05:11:21.081081088,4918.348711,7.027027
min,1.000000,92.000000,2023-02-01 00:00:00,285.000000,1.000000
25%,3.750000,429.000000,2023-09-06 00:00:00,1702.000000,5.000000
50%,6.000000,722.500000,2024-04-10 00:00:00,3466.500000,7.000000
75%,8.000000,969.500000,2024-09-07 00:00:00,7336.184211,10.000000
max,10.000000,2901.000000,2024-12-11 00:00:00,29010.000000,12.000000
std,2.842386,595.536493,NaN,4670.183610,3.192756